### ISSUE TITLE
urllib3 version update issue

### ISSUE THREAD

**Issue by UsamaSadiq** [edx/upgrades#114]
## Description
- `urllib3` package version has been upgraded to `urllib3>=2.0.0` in multiple repos during last week.
- After upgrading the version, the `make requirements` step started failing with `urllib3==2.0.2` (latest) version.
- See the https://github.com/urllib3/urllib3/issues/2168  issue for details regarding the reason for the failure.

## TODO
- Get the list of upgrade requirements PRs merged during last week in the repos
- Investigate the no. of repos in which `make requirements` step is failing due to the `urllib3` version. 
- If the issue is happening in more than one repos, create a PR in edx-lint to add common constraint `urllib3<2.0.0` in the [common_constraints.txt](https://github.com/openedx/edx-lint/blob/master/edx_lint/files/common_constraints.txt) file.
- Create a follow-up issue to remove the constraint once the underlying cause is fixed and comment it along the package constraint.

## Check List
- [ ] Add common constraint of `urllib3` in edx-lint
- [ ] Update requirements in the failing repos (e.g. edx-cookiecutters)
- [ ] Verify that the `make requirements` is now working as expected.

**Comment by UsamaSadiq** [comment]
As per the testing, we didn't face any issue in installing the package in any other repo at the moment so closing this issue as Done. We won't need to opt for the suggested approach in the issue.
